import 'package:flutter/material.dart';

class Locals {
  final Locale locals;

  Locals(this.locals);

  static Locals of(BuildContext context) {
    return Localizations.of(context, Locals)!;
  }

  static List<String> languages() {
    return localizedValue.keys.toList();
  }

  String greeting(String key) {
    try {
      if (localizedValue[locals.languageCode]![key] == null) {
        return key;
      }

      return localizedValue[locals.languageCode]![key]!;
    } on Exception {
      return key;
    }
  }

  static const localizedValue = <String, Map<String, String>>{
    'en': {
      'setting': 'Setting',
      'existed_customer': 'Cannot add new customer: An existing customer[:name] is within :kmkm.',
      'update_address': 'Update Address',
      'days_overdue': 'Overdue :day day(s)',
      'profile': 'Profile',
      'chang_password': 'Change Password',
      'must_within_store_checkin': 'You must be within :value meters of the store to check in.',
      'must_within_store_checkout': 'You must be within :value meters of the store to check out.',
      'logout': 'Logout',
      'logout_your_account': 'Logging out will stop access to your account data.',
      'connect_to': 'Connected To : ',
      'change_date': 'Change Date',
      'add_schedule': 'Add Schedule',
      'update_schedule': 'Update Schedule',
      'schedule': 'Schedule',
      'map_schedule': 'Map Schedule',
      'from_date': 'From Date',
      'to_date': 'To Date',
      'data_is_up_to_date': 'Data is up to date',
      'saleperson': 'Sale Person',
      'filters': 'Filters',
      'done': 'Done',
      'cancel': 'Cancel',
      'download': 'Download',
      'upload': 'Upload',
      'date': 'Date',
      'no_data': 'No Data',
      'status': 'Status',
      'ok': 'Ok',
      'mater_data': 'Master Data',
      'tran_data': 'Transaction Data',
      'save': 'Save',
      'numrow': 'No',
      'name': 'Name',
      'name_2': 'Name 2',
      'phoneno': 'Phone No',
      'email': 'Email',
      'address': 'Address',
      'address_2': 'Address 2',
      'customer': 'Customer',
      'customer_group': 'Customer Group',
      'customer_group_code': 'Customer group code:',
      'business_unit': 'Business Unit',
      'business_unit_code': 'Business unit code:',
      'store_code': 'Store code:',
      'store': 'Store:',
      'division_code': 'Division code:',
      'department_code': 'Department code:',
      'territory_code': 'Territory code:',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'pin_location_on_map': 'Pin location on map',
      'download_local_file': 'Download Local Files',
      'check_printer_status': 'Check Printer Status',
      'downloading_resources': 'Downloading Resources',
      'old_password': 'Old Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'confirm_password_change': 'Confirm Password Change',
      'do_you_want_to_download_local_resource_file': 'Do you want to download locale resource files?',
      'check_in': 'Check In',
      'gallery': 'Gallery',
      'camera': 'Open Camera',
      'write_a_comment': 'Write a comment',
      'shop_is_close': 'Shop is close',
      'check_stock': 'Check Stock',
      'sales_order': 'Sales Order',
      'sales_invoice': 'Sales Invoice',
      'sales_credit_memo': 'Sales Credit Memo',
      'collection': 'Collection',
      'count_remaining_quantity_of_items_at_customer_place': "Count remaining quantity of items at customer's place",
      'create_sales_order_for_customer': 'Create sales order for customer',
      'create_sale_invoice_for_customer': 'Create sales invoice for customer',
      'sales_credit_memo_for_customer': 'Create Credit Memo for customer',
      'collect_payment_from_the_customer': 'Collect payment from the customer',
      'logging_out': 'Logging out',
      'do_you_want_to_log_out': 'Do you want to log out?',
      'log_out': 'Log Out',
      'changing_date': 'Change Date',
      'update': 'UPDATE',
      'do_you_want_to_update_schedule': 'Do you want to update schedule?',
      'item': 'Items',
      'competitor_item': 'Competitor Item',
      'last_stock_holding': 'Last Stock Holding',
      'current_stock_holding': 'Current Stock Holding:',
      'edit_detail': 'Edit Detail',
      'na': 'N/A',
      'kg': 'KG',
      'submit': 'Submit',
      'quantity': 'Quantity',
      'qty_bought_from_others': 'Qty Bought From Other',
      'suggest_order_quantity': 'Suggest Order Quantity',
      'quantity_return': 'Quantity Return',
      'expiry_date': 'Expiry Date(YYYY-MM-DD)',
      'lot_no': 'Lot No',
      'serial_no': 'Serial No',
      'remark': 'Remark',
      'promotion': 'Promotion',
      'add_to_cart': 'Add To Cart',
      'free_of_charge': 'Free Of Charge',
      'discount_option_std': 'Discount Options - Standard Sales[STD]',
      'discount_percent': 'Discount(%)',
      'discount_amount': 'Discount amount',
      'manual_selling_price_std': 'Manual Selling Price - Standard Sales [STD]',
      'manual_price': 'Manual price',
      'this_will_overwrite_item_default_selling_price': ' This will overwrite item default selling price.',
      'apply': 'Apply Filter',
      'reset': 'Reset',
      'sale': 'Sales',
      'redemption': 'Redemption',
      'no_record': 'No Records',
      'customer_name': 'Customer Name',
      'document_no': 'Document No',
      'total_amount': 'Total Amount',
      'remaining_amount': 'Remaining Amount',
      'receive_amount': 'Receive Amount',
      'payment_type': 'Payment Type',
      'search': 'Search',
      'subtitle': 'Subtitle',
      'title': 'Title',
      'not_selected': 'Not Selected',
      'order_detail': 'Order Detail',
      'all': 'All',
      'approved': 'Approved',
      'open': 'Open',
      'closed': 'Closed',
      'edit_customer': 'Edit Customer',
      'customer_address': 'Customer Address',
      'option': 'Option',
      'product': 'Product',
      'document_date': 'Document Date',
      'request_shipment_date': 'Request Shipment Date',
      'ship_to_name': 'Ship To Name',
      'customer_no': 'Customer No',
      'customer_details': 'Customer Details',
      'document': 'Document',
      'number_of_records': 'Number Of Records',
      'last_download': 'Last Download',
      'menus': 'Menus',
      'sale_orders': 'Sale Orders',
      'sale_orders_detail': 'Sale Orders Details',
      'sale_invoices': 'Sale Invoices',
      'sale_invoice_details': 'Sale Invoice Details',
      'sale_credit_memo': 'Sale Credit Memo',
      'sale_credit_memo_detail': 'Sale Credit Memo Details',
      'customers': 'Customers',
      'promotions': 'Promotions',
      'code': 'Code',
      'code_dot': 'Code:',
      'my_schedule': 'My Schedule',
      'team_schedule': 'Team Schedule',
      'process': 'Process',
      'order': 'Order',
      'credit_memo': 'Credit Memo',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'phone_number': 'Phone Number',
      'language': 'Language',
      'khmer': 'Khmer',
      'english': 'English',
      "please_input_your_quantity_below.": "Please input your quantity below.",

      /**
       * Report Screen word
       */
      'so_outstanding': 'SO Outstanding',
      'daily_sales_summary': 'Daily Sales Summary',
      'customer_balance': 'Customer Balance',
      'inventory': 'Inventory',
      'item_inventory': 'Item Inventory',
      'stock_request': 'Stock Request',
      'stock_request_details': 'Stock Request Details',
      'item_redemption_by_sales_person': 'Item Redemption by Salesperson',
      'item_redemption': 'Item Redemption',
      'submit_items': 'Submit Items',
      'create_schedules': 'Create Schedules',
      'please_process_transactions_before_checking_out': 'Please process transactions before checking out',
      "preview": "Previews",
      "cancel_request": "Cancel Request",
      "recive_stock": "Recive Stock",
      "filter": "Filter",
      "salesperson_code": "Salesperson Code",

      /**
       * Main screen word
       */
      'task': 'Task',
      'stock': 'Stock',
      'report': 'Report',
      'notification': 'Notification',
      'more': 'More',
      'mores': 'Mores',
      'administration': 'Administration',
      'reset_password': 'Reset Password',
      'about': 'About',
      'login': 'Login',
      'email_id': 'Email ID',
      'forget_pass': 'Forget Password ?',

      /**
       * So Outstanding
       */
      'date_title': 'Date Title',
      'description': 'Description',

      /**
       * Inventory
       */
      'no_description': 'No / Description',
      'please_insert_the_url_link': 'Please insert the URL link.',
      'url_link': 'URL link',
      'do_you_want_to_delete': 'Do you want to delete?',
      'or': 'OR',
      'use_with_other_acc': 'Use with other account',
      'please_select_server_below': 'Please select server below.',
      'connected_to': 'Connected to : ',
      'choose_option_below.': 'Choose option below.',
      'no_record_found.': "The record is not found!",
      'You_can_not_be_visiting_this_schedule':
          "You can not be visiting this schedule!\nbecause you did not yet visit your old schedule\nPlease process your old schedule first.",
      'there_is_pending_checkin_schedule': "There are pending check-in schedule",
      'take_the_photo': "Please take the photo",
      'tap_to_upload_picture': "Tap to upload picture",
      'continue_to_submit': "Continue to submit",
      'tasks': "Tasks",
      'do_you_want_to_create': "Do you want to create the customer schedules.",
      'add_schedules': "Add Schedules",
      'check_out': "Check Out",
      'items': "Items",
      'competitor_items': "Competitor Items",
      'edit_details': "Edit Details",
      'qty_bought_form_other': "Purchased from others",
      'suggest_order_qty': "Suggested order quantity",
      'please_submit_pending_process_before_checking_out': 'Please submit pending process before checking out',
      'qty_return': 'Return quantity',
      'write_remark_here...': 'Write remark here...',
      'user_set_up_not_found': 'User set up not found!',
      'process_cart': 'Process Cart',
      'sell_qty': 'Sale quantity',
      'unit': 'Unit',
      'fee_charge': 'Free of charge',
      'discount_option_standard_sales': 'Discount Options - Standard Sales [STD]',
      'manual_selling_price_standard_sales': 'Manual Selling Price - Standard Sales [STD]',
      'manual_price_dollar': 'Manual Price',
      "required_access_location": "Enable location to continue.",
      "you_has_any_pending_schedule": "You have some pending schedules.",
      "this_record_not_found!": "This schedule is not found.",
      "please_check_in_before_process": "Please check in before proceeding.",
      "record_not_found": "Record not found.",
      "customer_location": "Customer Location",
      "set_location": "Set Location",
      "schedule_history": "Schedule History",
      "schedule_date": "Schedule Date",
      "comments_field_require": "Comment field required",
      "invalid_line_id_request": "Invalid line ID request.",
      "TMP_sales_shipment_planing_not_found": "TMP sales shipment planing not found",
      "other_optional": "Other (Optional)",
      "clear": "Clear",
      "dis_percentage_must_rang0_100": "Discount percentage cannot greater than 100%",
      "groups": "Goups",
      "customer_information": "Customer Information",
      "no": "No:",
      "posm": "POSM",
      "merchanding_item": "Merchading Item",
      "merchanding": "Merchanding",
      "posm_item": "POSM Item",
      "posting_date_from": "Date from : ",
      "select_date": "Selected Date",
      "choose_sale_person": "Select SalePerson",
      "volume_sale": "Volume Sale",
      "unit_price": "Unit Price",
      "unit_cost": "Unit Cost",
      "competitor_items_from": "Competitor Item Form",
      'edit_cart': 'Edit Cart',
      "competitor_promotion": "Competitor Promotion",
      "redempt_item_programs_for_the_customers": "Redempt item programs for the customers",
      "item_prize_redemption": "Item prize redemption",
      "take_note_competitor's_promotion.": "take note competitor's promotion.",
      "call_now": "Call Now",
      "do_you_want_to_submit_now?": "Do you want to submit now?",
      "customer_already_exists": "Customer already exists",
      "new_payment": "New Payment",
      "delete": "Delete",
      "do_you_want_to_delete_new_payment?": "Do you want to delete new payment?",
      "detials": "Detials",
      "receive_amoun_require": "Receive amount is require!",
      "payment_method_require": "Payment method is require!",
      "receive_amount_can_not_greater": "Receive amount can not greater than invoice remaining amount!",
      "are_you_sure_to_submit_all_receipt?": "Are you sure to submit all the receipts?",
      "do_you_want_to_delete_?": "Do you want to delete?",
      "customer_adddress_save_successfully": "Customer adddress save successfully",
      "customer_change_successfully": "Customer change successfully",
      "no_of_invoices": "No. of Invoices:",
      "no_of_credit_memo": "No. of Credit Memo:",
      "are_you_sure_to_delete": "Are you sure to deleted",
      "total_sales_amount": "Total Sales Amount:",
      "total_sales_amount_coh": "Total Sales Amount(COH):",
      "total_credit_memo_amount": "Total Credit Memo Amount:",
      "total_balance": "Total Balance:",
      "total_collection": "Total Collection:",
      "total_amount_recived": "Total Amount Recieved:",
      "today_schedule": "Today's Schedule",
      "view_detail": "View Details",
      "order_items": " Order Items",
      "ship_to": " Ship To",
      "ship_date": "Ship Date",
      "filter_options": "Filter Options",
      "date_range": "Date Range",
      "to": "To",
      "sale_invoice": "Sale Invoice",
      "apply_filter": "Apply Filter",
      "reset_filter": "Reset Filter",
      "merchandising_sub_title": "Count merchandising items at customer's place",
      "posm_subtitle": "Count POSM items at customer's place",
      "sales_person": "Sales Person",
      "edit": "Edit",
      "add_address": "Add Adress",
      "cutomer_info": "Info",
      "cutomer_address": "Address",
      "customer_info": "Customer Info",
      "full_name": "Full Name",
      "address_map": "Map Address",
      "add_new_address": "Add New Address",
      "Street_address": "Street Address",
      "address_info": "Address Info",
      "city": "City",
      "contry": "Country",
      "currently_address": "Currently Address",
      "current_location": "Current Location",
      "see_map": "Open Map",
      "create_address": "Create Address",
      "save_address": "Save Address",
      "address_name": "Address Name",
      "code_address": "Code",
      "code_customer": "Customer Code",
      "inventory_management": "Inventory Management",
      "sale_&_finance": "Sales & Finance",
      "operations": "Operations",
      "manage_and_track all sale orders": "Manage and track all sale orders",
      "generate_and_manage_invoice": "Generate and manage invoice",
      "process_returns_and_refunds": "Process return and refund",
      "create_customers_add_addres": "Manage customer and  address",
      "manage_promotion": "Manage all the promotions",
      "download_data_from_setup":
          "Download all necessary data from the server to initialize the app and enable offline usage.",
      "upload_data_to_server": "Upload data to server",
      //   "manage_and_track all sale orders": "Manage and track all sale orders",
      //   "manage_and_track all sale orders": "Manage and track all sale orders",
      "request_qty": "REQUEST",
      "accepted_qty": "ACCEPT",
      "shipped_qty": "SHIPPED",
      "recieved": "RECIEVED",
      "total_items": "Total Items",
      "total_quantity": "Total Quantity",
      "item_prize_redemtion": "Item Prize Redemption",
      "track_order_ship_pending": "Tracks shipped,pending items.",
      "overview_summary_of_sale_performance": "Overview Summary of sales performance.",
      "outstadind_amount_the_customer_owes": "Outstanding amount the customer owes",
      "effficiently_manage_stock_levels_and_availability": "Efficiently manage stock levels and availability",
      "manage_and_track_stock_replenishment_request": "Manage and track stock replenishment requests",
      "manage_redemptions_made_by_saleperson": "Manage redemptions made by salespersons.",
      "account_management_and_permissions": "Account management and permissions",
      "account_&_security": "Account & Security",
      "change_your_account_password": "Change your account password",
      "app_version_and_legal_information": "App version and legal information",
      "support": "Support",
      "out_of_stock": "Out of stock",
      "posting_date": "Posting Date",
      "sale_amount": "Sale Amount",
      "invoice": "INVOICE",
      "paid_amount": "Paid Amount",
      "current_password": "Current Password",
      "please_fill_all_fields": "Please fill all fields",
      "password_not_match": "Password not matching. Please try again.",
    },
    'km': {
      "password_not_match": "ពាក្យសម្ងាត់មិនត្រូវគ្នា។ សូមព្យាយាមម្តងទៀត។",
      "please_fill_all_fields": "សូមបំពេញវាលទាំងអស់",
      'existed_customer': 'មិនអាចបន្ថែមអតិថិជនថ្មីបានទេ៖ អតិថិជនដែលមានស្រាប់ស្ថិតនៅក្នុងរង្វង់ :km គីឡូម៉ែត្រ។',
      "current_password": "ពាក្យសម្ងាត់បច្ចុប្បន្ន",
      "support": "គាំទ្រអតិថិជន",
      "app_version_and_legal_information": "កំណែកម្មវិធី និងព័ត៌មានផ្លូវច្បាប់",
      "change_your_account_password": "ផ្លាស់ប្តូរពាក្យសម្ងាត់គណនីរបស់អ្នក",
      "account_&_security": "គណនី និងសុវត្ថិភាព",
      "account_management_and_permissions": "ការគ្រប់គ្រងគណនី និងការអនុញ្ញាត",
      "manage_redemptions_made_by_saleperson": "គ្រប់គ្រងការបង្វិលទំនិញដោយបុគ្គលិកលក់",
      "manage_and_track_stock_replenishment_request": "គ្រប់គ្រងនិងតាមដានសំណើសុំស្តុក",
      "effficiently_manage_stock_levels_and_availability": "គ្រប់គ្រងកម្រិតស្តុក និងភាពមាននៅលើទំនិញ",
      "outstadind_amount_the_customer_owes": "ចំនួនប្រាក់សរុបដែលអតិថិជននៅតែជំពាក់ និងមិនទាន់បានបង់",
      "overview_summary_of_sale_performance": "ទិដ្ឋភាពទូទៅ សង្ខេបនៃប្រតិបត្តិការលក់",
      "track_order_ship_pending": "តាមដានទំនិញដែលបានបញ្ជាទិញ ដឹកជញ្ជូន និងទំនិញដែលមិនទាន់សម្រេច",
      "item_prize_redemtion": "ការទៅយករង្វាន់",
      "paid_amount": "ប្រាក់បានបង់",
      "invoice": "វិក័យប័ត្រ",
      "sale_amount": "បរិមាណលក់",
      "posting_date": "កាលបរិច្ឆេទប្រកាស",
      "out_of_stock": "អស់ពីស្តុក",
      "upload_data_to_server": "ផ្ទុកទិន្នន័យឡើងទៅម៉ាស៊ីនមេ",
      "manage_and_track all sale orders": "គ្រប់គ្រង និងតាមដានរាល់ការបញ្ជាទិញលក់",
      "generate_and_manage_invoice": "បង្កើត និងគ្រប់គ្រងវិក្កយបត្រ",
      "process_returns_and_refunds": "ដំណើរការត្រឡប់ និងសងប្រាក់វិញ",
      "create_customers_add_addres": "គ្រប់គ្រងអតិថិជន និងអាសយដ្ឋាន",
      "manage_promotion": "គ្រប់គ្រងការផ្សព្វផ្សាយទាំងអស់",
      "download_data_from_setup": "ទាញយកទិន្នន័យទាំងអស់ពីម៉ាស៊ីនមេសម្រាប់ការចាប់ផ្តើមប្រើប្រាស់កម្មវិធី",
      "operations": "ប្រតិបត្តិការ",
      "total_items": "ធាតុសរុប",
      "total_quantity": "បរិមាណសរុប",
      "recieved": "បានទទួល",
      "shipped_qty": "ដឹកជញ្ជូន",
      "accepted_qty": "យល់ព្រម",
      "request_qty": "ស្នើសុំ",
      "sale_&_finance": "ការលក់ និងហិរញ្ញវត្ថុ",
      "inventory_management": "ការគ្រប់គ្រងសារពើភ័ណ្ឌ",
      "code_customer": "លេខកូដអតិថិជន",
      "code_address": "Code",
      "address_name": "ឈ្មោះអាសយដ្ឋាន",
      "save_address": "រក្សាទុកអាសយដ្ឋាន",
      "create_address": "បង្កើតអាសយដ្ឋាន",
      "see_map": "មើលផែនទី",
      "current_location": "ទីតាំងបច្ចុប្បន្ន",
      "currently_address": "អាសយដ្ឋានបច្ចុប្បន្ន",
      "city": "ទីក្រុង",
      "contry": "ប្រទេស",
      "address_info": "ព័ត៌មានអាសយដ្ឋាន",
      "Street_address": "អាស័យដ្ឋានផ្លូវ",
      "add_new_address": "បន្ថែមអាសយដ្ឋានថ្មី",
      "address_map": "អាសយដ្ឋានផែនទី",
      "full_name": "ឈ្មោះពេញ",
      "customer_info": "ព័ត៌មានអតិថិជន",
      "cutomer_address": "អាសយដ្ឋានអតិថិជន",
      "cutomer_info": "ព័ត៌មានអតិថិជន",
      "add_address": "បន្ថែមអាសយដ្ឋាន",
      "edit": "កែសម្រួល",
      "sales_person": "អ្នកលក់",
      "reset_filter": " សម្អាតតម្រង",
      "apply_filter": " អនុវត្តតម្រង",
      'days_overdue': 'ហួស :day ថ្ងៃ',
      "sale_invoice": " វិក្កយបត្រ​លក់",
      "to": "ទៅកាន់",
      "date_range": " រយៈពេលកាលបរិច្ឆេទ",
      "filter_options": " ជម្រើសតម្រង",
      "ship_date": " ថ្ងៃដឹកជញ្ជូន",
      "ship_to": " ទៅកាន់",
      "order_items": " ធាតុបញ្ជាទិញ",
      "view_detail": "មើលព័ត៌មានលម្អិត",
      "are_you_sure_to_delete": "តើអ្នកប្រាកដក្នុងការលុប ",
      "are_you_sure_to_submit_all_receipt?": "តើអ្នកប្រាកដក្នុងការបញ្ជូនបង្កាន់ដៃទាំងអស់ទេ?",
      "receive_amount_can_not_greater": "ចំនួនទឹកប្រាក់ទទួលមិនអាចធំជាងចំនួនទឹកប្រាក់ដែលនៅសល់ក្នុងវិក្កយបត្រ!",
      "receive_amoun_require": "ត្រូវការចំនួនទឹកប្រាក់ដែលត្រូវទទួល!",
      "detials": "ព័ត៌មានលម្អិត",
      "customer_adddress_save_successfully": "រក្សាទុកអាសយដ្ឋានអតិថិជនដោយជោគជ័យ",
      "total_amount_recived": "ចំនួនសរុបដែលទទួលបាន:",
      "total_collection": "ចំនួនប្រមូល:",
      "total_balance": "ចំនួនជំពាក់:",
      "total_credit_memo_amount": "ចំនួនលក់បង្វិលទំនិញសរុប:",
      "total_sales_amount": "ចំនួនលក់សរុប:",
      "total_sales_amount_coh": "ចំនួនលក់សរុប(COH):",
      "no_of_invoices": "លេខនៃវិក្កយបត្រ:",
      "no_of_credit_memo": "លេខនៃបង្វិលទំនិញ:",
      "customer_change_successfully": "ការផ្លាស់ប្តូរអតិថិជនដោយជោគជ័យ",
      "do_you_want_to_delete_?": "តើអ្នកចង់លុបទេ?",
      "delete": "លុប",
      "new_payment": "ការទូទាត់ថ្មី",
      "do_you_want_to_submit_now?": "តើអ្នកចង់ដាក់ស្នើឥឡូវនេះទេ?",
      "call_now": "ហៅឥឡូវនេះ",
      "take_note_competitor's_promotion.": "កត់សម្គាល់ការផ្សព្វផ្សាយរបស់គូប្រកួត",
      "item_prize_redemption": "ការប្ដូររង្វាន់ទំនិញ",
      "redempt_item_programs_for_the_customers": "កម្មវិធីប្ដូររង្វាន់សម្រាប់អតិថិជន",
      'edit_cart': 'កែប្រែ',
      "competitor_promotion": "ការផ្សព្វផ្សាយរបស់គូប្រជែង",
      "competitor_items_from": "ទម្រង់​មុខ​ទំនិញ​គូ​ប្រជែង",
      "unit_cost": "តម្លៃឯកតា",
      "unit_price": "តម្លៃឯកតា",
      "volume_sale": "បរិមាណលក់",
      "choose_sale_person": "ជ្រើសរើស SalePerson",
      "select_date": "កាលបរិច្ឆេទដែលបានជ្រើសរើស",
      "posting_date_from": "កាលបរិច្ឆេទពី : ",
      "salesperson_code": "លេខ​កូដ​អ្នក​លក់",
      "posm_item": "ទំនិញសម្ភារៈប្រើនៅចំណុចលក់",
      "merchanding": "ផ្សព្វផ្សាយទំនិញ",
      "merchanding_item": " ទំនិញផ្សព្វផ្សាយ",
      "posm": "ផ្សព្វផ្សាយផលិតផលនៅចំណុចលក់",
      "groups": "ក្រុម",
      "filter": "តម្រង",
      "no": "ល.រ:",
      "customer_information": "ព័ត៌មានអតិថិជន",
      "dis_percentage_must_rang0_100": "ចំនួនបញ្ចុះតម្លៃមិនអាចលើសពី 100%",
      "clear": "សម្អាត",
      "TMP_sales_shipment_planing_not_found": "រកមិនឃើញការធ្វើផែនការដឹកជញ្ជូនលក់ TMP ទេ.",
      "invalid_line_id_request": "សំណើរ Line ID មិនត្រឹមត្រូវទេ.",
      "comments_field_require": "តម្រូវ​ឱ្យ​មាន​វាល​មតិ",
      "schedule_date": "កាលបរិច្ឆេទកាលវិភាគ",
      "schedule_history": "ប្រវត្តិកាលវិភាគ",
      "customer_location": "ទីតាំងអតិថិជន",
      "set_location": "កំណត់ទីតាំង",
      "record_not_found": "មិនមានកំណត់ត្រា",
      "please_check_in_before_process": "សូមចុះឈ្មោះចូលមុននឹងបន្ត",
      "this_record_not_found!": "កាលវិភាគនេះមិនត្រូវបានរកឃើញទេ",
      "you_has_any_pending_schedule": "អ្នកមានកាលវិភាគដែលមិនទាន់បញ្ចប់",
      "required_access_location": "កម្មវិធីត្រូវការចូលប្រើទីតាំងបច្ចុប្បន្នរបស់អ្នក",
      'manual_price_dollar': 'កែប្រែតម្លៃ',
      'manual_selling_price_standard_sales': 'តម្លៃលក់ដោយដៃ - លក់ស្តង់ដា [STD]',
      'discount_amount_(Dollar)': 'ចំនួនទឹកប្រាក់បញ្ចុះតម្លៃ (\$)',
      'discount_%': 'បញ្ចុះតម្លៃ (%)',
      'discount_option_standard_sales': 'ជម្រើសបញ្ចុះតម្លៃ - លក់ស្តង់ដា [STD]',
      'fee_charge': 'ទំនិញហ្វី',
      'unit': 'ឯកតា',
      'sell_qty': 'ចំនួនលក់',
      'process_cart': 'រទេះដំណើរការ',
      'user_set_up_not_found': 'រក​មិន​ឃើញ​អ្នក​ប្រើ​ដំឡើង!',
      'write_remark_here...': 'សរសេរចំណាំនៅទីនេះ...',
      'qty_return': 'Qty ត្រឡប់មកវិញ',
      'suggest_order_qty': "ណែនាំបរិមាណបញ្ជាទិញ",
      'qty_bought_form_other': "Qty បានទិញពីអ្នកដទៃ",
      'edit_details': "កែសម្រួលព័ត៌មានលម្អិត",
      'items': "ធាតុ",
      'competitor_items': "ធាតុរបស់ដៃគូប្រកួតប្រជែង",
      'please_process_transactions_before_checking_out': 'សូមដំណើរការប្រតិបត្តិការមុនពេលចេញ',
      'please_submit_pending_process_before_checking_out': 'សូមបញ្ជូនដំណើរការដែលមិនទាន់សម្រេចមុនពេលចេញ',
      'check_out': "ពិនិត្យចេញ",
      'add_schedules': "បន្ថែមកាលវិភាគ",
      'do_you_want_to_create': "តើអ្នកចង់បង្កើតកាលវិភាគអតិថិជនដែរឬទេ?",
      'tasks': "កិច្ចការ",
      'continue_to_submit': "បន្តដាក់ស្នើ",
      'tap_to_upload_picture': "ប៉ះដើម្បីបង្ហោះរូបភាព",
      'take_the_photo': "សូមថតរូប",
      'there_is_pending_checkin_schedule': "មានកាលវិភាគពិនិត្យចូលដែលមិនទាន់សម្រេច",
      'You_can_not_be_visiting_this_schedule':
          "អ្នកមិនអាចចូលមើលកាលវិភាគនេះបានទេ!\nព្រោះអ្នកមិនទាន់បានចូលមើលកាលវិភាគចាស់របស់អ្នកទេ\nសូមដំណើរការកាលវិភាគចាស់របស់អ្នកជាមុនសិន។",
      'no_record_found.': "រកមិនឃើញកំណត់ត្រាទេ!",
      'choose_option_below.': 'ជ្រើសរើសជម្រើសខាងក្រោម',
      'connected_to': 'បានភ្ជាប់ទៅ ៖   ',
      'please_select_server_below.': 'សូមជ្រើសរើសម៉ាស៊ីនមេខាងក្រោម',
      'use_with_other_acc': 'ប្រើជាមួយគណនីផ្សេងទៀត',
      'or': 'ឬ',
      'do_you_want_to_delete': 'តើអ្នកចង់លុបទេ?',
      'create_schedules': 'បង្កើតកាលវិភាគ',
      'forget_pass': 'ភ្លេចពាក្យសម្ងាត់?',
      'email_id': 'អ៊ីមែល',
      'setting': 'កំណត់',
      'profile': 'ប្រូហ្វាល់',
      'chang_password': 'ប្តូរលេខសម្ងាត់',
      'logout': 'ចាកចេញ',
      'login': 'ចូលដំណើរការគណនី',
      'connect_to': 'ភ្ជាប់ទៅ : ',
      'change_date': 'ប្តូរកាលបរិច្ឆេទ',
      'add_schedule': 'បង្កើរកាលវិភាគ',
      'update_schedule': 'កែប្រែកាលបរិច្ឆេទ',
      'schedule': 'កាលបរិច្ឆេទ',
      'map_schedule': 'ទីតាំងកាលបរិច្ឆេទ',
      'from_date': 'ចាប់ថ្ងៃ',
      'to_date': 'ដល់ថ្ងៃ',
      'data_is_up_to_date': 'ទិន្នន័យបានធ្វើបច្ចុប្បន្នភាព',
      'saleperson': 'អ្នកលក់',
      'filters': 'តម្រង',
      'done': 'រួចរាល់',
      'cancel': 'បោះបង់',
      'download': 'ទាញយក',
      'upload': 'បញ្ចូល',
      'date': 'កាលបរិច្ឆេទ:',
      'no_data': 'មិនមានទិន្នន័យ',
      'status': 'ស្ថានភាព',
      'ok': 'យល់ព្រម',
      'masterdata': 'ទិន្នន័យចម្បង',
      'transactiondata': 'ប្រតិបត្តិការទិន្នន័យ',
      'save': 'រក្សាទុក',
      'numrow': 'ល.រ',
      'name': 'ឈ្មោះ:',
      'name_2': 'ឈ្មោះ 2:',
      'phoneno': 'លេខ:',
      'email': 'អ៊ីម៉ែល:',
      'address': 'ទីតាំង:',
      'address_2': 'ទីតាំង 2:',
      'customer': 'អតិថិជន',
      'customer_details': 'ព័ត៌មានលំអិតរបស់អតិថិជន',
      'customer_group': 'ក្រុមអតិថិជន',
      'customer_group_code': 'កូដក្រុមអតិថិជន:',
      'business_unit': 'Business Unit',
      'business_unit_code': 'Business unit code:',
      'store_code': 'កូដហាង:',
      'store': 'ហាង:',
      'division_code': 'Division code:',
      'department_code': 'កូដនាយកដ្ធាន:',
      'territory_code': 'កូដដំបន់:',
      'latitude': 'រយៈទទឹង:',
      'longitude': 'រយៈបណ្តោយ:',
      'pin_location_on_map': 'កំណត់ទីតាំងលើផែនទី',
      'download_local_file': 'ទាញយកទិន្នន័យ',
      'check_printer_status': 'ពិនិត្យស្ថានភាពម៉ាស៊ីនព្រីន',
      'downloading_resources': 'កំពុងទាញយកទិន្នន័យ',
      'old_password': 'លេខសម្ងាត់ចាស់',
      'new_password': 'លេខសម្ងាត់ថ្មី',
      'confirm_password': 'បញ្ជាក់លេខសម្ងាត់',
      'confirm_password_change': 'ប្តូរលេខសម្ងាត់',
      'do_you_want_to_download_local_resource_file': 'តើអ្នកចង់ទាញយកទិន្នន័យឬ?',
      'check_in': 'ចូល',
      'gallery': 'វិចិត្រសាល',
      'camera': 'កាមេរ៉ា',
      'write_a_comment': 'សរសេរមតិ',
      'shop_is_close': 'ហាងបានបិទ',
      'check_stock': 'ពិនិត្យស្តុក',
      'sales_order': 'បញ្ជាទិញលក់',
      'sales_invoice': 'វិក្កយបត្រលក់',
      'sales_credit_memo': 'បង់វិលទំនិញលក់',
      'collection': 'ការប្រមូល',
      'count_remaining_quantity_of_items_at_customer_place': "រាប់ចំនួនធាតុដែលមាននៅកន្លែងអតិថិជន",
      'create_sales_order_for_customer': 'បង្កើតការបញ្ជាទិញលក់អោយអតិជិជន',
      'create_sale_invoice_for_customer': 'បង្កើតវិក្កយបត្រការលក់អោយអតិថិជន',
      'sales_credit_memo_for_customer': 'បង្កើតការបង្វិលទំនិញអោយអតិជន',
      'collect_payment_from_the_customer': 'ប្រមូលការទូទាត់ពិអតិថិជន',
      'logging_out': 'ចាកចេញ',
      'do_you_want_to_log_out': 'តើអ្នកចង់ចាកចេញឬ?',
      'log_out': 'ចាកចេញ',
      'changing_date': 'ប្តូរកាលបរិច្ឆេទ',
      'update': 'ធ្វើបច្ចុប្បន្នភាព',
      'do_you_want_to_update_schedule': 'តើអ្នកចង់ធ្វើបច្ចុប្បន្នភាពកាលវិភាគឬ?',
      'item': 'ធាតុ',
      'competitor_item': 'ធាតុប្រកួតប្រជែង',
      'last_stock_holding': 'ស្តុកចុងក្រោយ',
      'current_stock_holding': 'ស្តុកបច្ចុប្បន្ន:',
      'edit_detail': 'កែប្រែការលម្អិត',
      'na': 'គ្មាន',
      'kg': 'KG',
      'submit': 'បញ្ជូន',
      'quantity': 'ចំនួន',
      'qty_bought_from_others': 'ចំនួនបានទិញពីក្រៅ',
      'suggest_order_quantity': 'ណែនាំចំនួនកម្មង់',
      'quantity_return': 'ចំនួនត្រលប់មកវិញ',
      'expiry_date': 'កាលបរិច្ឆេទហួសកំណត់(ឆ្នាំ-ខែ-ថ្ងៃ)',
      'lot_no': 'លេខ Lot',
      'serial_no': 'លេខ Serial',
      'remark': 'ចំណាំ',
      'promotion': 'ប្រម៉ូសិន',
      'add_to_cart': 'ដាក់ចូលកន្ត្រក',
      'free_of_charge': 'ឥតគិតថ្លៃ',
      'discount_option_std': 'ជម្រើសបញ្ចុះតម្លៃ - ការលក់ស្តង់ដារ[STD]',
      'discount_percent': 'បញ្ចុះតម្លៃ (%)',
      'discount_amount': 'បញ្ចុះតម្លៃសរុប',
      'manual_selling_price_std': 'តម្លៃលក់ដោយដៃ - ការលក់ស្តង់ដារ[STD]',
      'manual_price': 'តម្លៃដោយដៃ',
      'this_will_overwrite_item_default_selling_price': '* តម្លៃលក់និងប្តូរតាមតម្លៃដែលអ្នកបញ្ចូល',
      'apply': 'អនុវត្ត',
      'reset': 'កំណត់ឡើងវិញ',
      'sale': 'ការលក់',
      'redemption': 'ការប្តូរទំនិញ',
      'no_record': 'មិនមានទិន្នន័យ',
      'customer_name': 'ឈ្មោះអតិថិនជន',
      'document_no': 'លេខឯកសារ',
      'total_amount': 'ចំនួនទឹកប្រាក់សរុប',
      'remaining_amount': 'ចំនួនទឹកប្រាក់ដែលនៅសល់',
      'receive_amount': 'ចំនួនទឹកប្រាក់ដែលទទួល',
      'payment_type': 'ប្រភេទទូទាត់',
      'search': 'ស្វែករក',
      'subtitle': 'ឈ្មោះរង',
      'title': 'ឈ្មោះ',
      'not_selected': 'មិនទាន់ជ្រើសរើស',
      'order_detail': 'លម្អិតការកម្មង់',
      'all': 'ទាំងអស់',
      'approved': 'បានអនុម័ត',
      'open': 'បើក',
      'closed': 'បានបិទ',
      'edit_customer': 'កែប្រែអតិថិជន',
      'customer_address': 'អាសយដ្ធានអតិថិជន',
      'option': 'ជម្រើស',
      'product': 'ផលិតផល',
      'document_date': 'កាលបរិច្ឆេទឯកសារ',
      'request_shipment_date': 'ស្នើរកាលបរិច្ឆេទដឹកជញ្ជូន',
      'ship_to_name': 'ដឹកជញ្ជូទៅឈ្មោះ',
      'customer_no': 'លេខអតិថិជន',
      'document': 'ឯកសារ',
      'number_of_records': 'ចំនួនទិន្នន័យ',
      'last_download': 'ការទាញយកចុងក្រោយ',
      'menus': 'ម៉ឺនុយ',
      'sale_orders': 'ការបញ្ជាទិញ',
      'sale_orders_detail': 'ព័ត៌មានលម្អិតនៃការបញ្ជាទិញ',
      'sale_invoices': 'វិកាយបត្រការលក់',
      'sale_invoice_details': 'ព័ត៌មានលម្អិតអំពីវិក្កយបត្រលក់',
      'sale_credit_memo': 'ការបង់វិលទំនិញលក់',
      'sale_credit_memo_detail': 'ព័ត៌មានលម្អិតអំពីការលក់ឥណទាន',
      'customers': 'អតិថិជន',
      'promotions': 'ប្រម៉ូសិន',
      'code': 'កូដ',
      'code_dot': 'កូដ:',
      'my_schedule': 'កាលវិភាគរបស់ខ្ញុំ',
      'team_schedule': 'កាលវិភាគក្រុម',
      'process': 'ដំណើរការ',
      'order': 'កម្មង់',
      'credit_memo': 'បង្វិលទំនិញ',
      'first_name': 'នាមត្រកូល',
      'last_name': 'នាមខ្លួន',
      'phone_number': 'លេខទូរស័ព្ទ',
      'langauge': 'ភាសា',
      'khmer': 'ខ្មែរ',
      'english': 'អង់គ្លេស',

      /**
       * Report Screen word
       */
      'so_outstanding': 'SO Outstanding',
      'daily_sales_summary': 'សង្ខេបការលក់ប្រចាំ',
      'customer_balance': 'សមតុល្យអតិថិជន',
      'inventory': 'សារពើភ័ណ្ឌ',
      'item_inventory': 'ស្តុកទំនិញ',
      'stock_request': 'ស្នើរស្តុក',
      'stock_request_details': 'ព័ត៌មានស្នើរស្តុក',
      'item_redemption_by_sales_person': 'ទំនិញប្តូរដោយអ្នកលក់',
      'item_redemption': 'ការប្តូរទំនិញ',

      /**
       * Main screen word
       */
      'task': 'កិច្ចការ',
      'stock': 'ស្តុក',
      'report': 'ការបាយការណ៍',
      'notification': 'ការផ្តល់ដំណឹង',
      'more': 'បន្ថែម',
      'mores': 'បន្ថែម',
      'administration': 'ការគ្រប់គ្រង',
      'reset_password': 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
      'about': 'អំពី',

      /**
       * So Outstanding
       */
      'date_title': 'កាលបរិច្ឆេទ',
      'description': 'បរិយាយ',

      /**
       * Inventory
       */
      'no_description': 'លេខរៀង / បរិយាយ',
      "other_optional": "ជម្រើសផ្សេងទៀត",
      "customer_already_exists": "អតិថិជនមានរួចហើយ"
    }
  };
}
